// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc2465.Hercules.commands;
import java.util.concurrent.DelayQueue;

import org.usfirst.frc2465.Hercules.Robot;
import org.usfirst.frc2465.Hercules.RobotMap;

import edu.wpi.first.wpilibj.command.Command;
//import edu.wpi.first.wpilibj.command.Command;
import edu.wpi.first.wpilibj.command.CommandGroup;
import edu.wpi.first.wpilibj.command.WaitCommand;

/**
 *
 */

public class FinalGear extends CommandGroup {
	float desired_angle;
    public FinalGear(float desired_angle) {
    	this.desired_angle = desired_angle;
    	this.addSequential(new TiltPincherU());
    	this.addSequential(new DriveDistance(12f, 0.1f, 0.0f));
    	this.addSequential(new OpenPincher());
    	this.addSequential(new WaitCommand(0.25));
    	this.addSequential(new Deploy());
    	this.addSequential(new WaitCommand(0.5));

    	this.addSequential(new DriveDistance(-14f, -0.1f, 0.0f));

    }

    // Called just before this Command runs the first time
    protected void initialize() {
    }

    // Called repeatedly when this Command is scheduled to run
    protected void execute() {
    	Robot.drive.setAutoRotation(true);
    	Robot.drive.setSetpoint(desired_angle);
    }

    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
        return false;
    }

    // Called once after isFinished returns true
    protected void end() {
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
    }
}
